### ISSUE TITLE
关于修改sw文件夹

### ISSUE THREAD

**Issue by 0xwhatly** [yinwhm12/fabricGM#2]
想请教下，既然添加了bccsop/gm目录，对应的gm操作都实现了，为什么还要在SW中添加国密的选项，GM和SW两者在使用的时候不能做到独立嘛？

**Comment by yinwhm12** [comment]
其实bccsp/sw是主要的，大部分gm的东西都在sw中实现了的；你可以把gm做对应的调整删除；bccsp/gm主要是为了解读理解单独出来而已；再者，两者使用的时候是可以做到独立的，但是GetDefaultOpts()函数部分必须修改。
