### ISSUE TITLE
TLS通信

### ISSUE THREAD

**Issue by bhtdz-zhou** [yinwhm12/fabricGM#3]
作者您好，麻烦问一下你改造的这个国密版本底层通信是否也支持国密算法来实现SSL呢

**Comment by yinwhm12** [comment]
您好，这个是支持的。

**Comment by bhtdz-zhou** [comment]
> 您好，这个是支持的。

非常感谢您的回复，fabric支持国密TLS通信的话:
1、比如我用fabric-sdk-java和fabric交互，sdk底层通信用的是netty和openssl来实现，那是不是这两个也得改造才行呢?
2、如第一点实现不了的话，那能不能这样：sdk端底层不动，通信走的还是原生ECC算法 ，对数据的处理用国密算法，这种做目前版本是否支持呢？

**Comment by yinwhm12** [comment]
> > 您好，这个是支持的。
> 
> 非常感谢您的回复，fabric支持国密TLS通信的话:
> 1、比如我用fabric-sdk-java和fabric交互，sdk底层通信用的是netty和openssl来实现，那是不是这两个也得改造才行呢?
> 2、如第一点实现不了的话，那能不能这样：sdk端底层不动，通信走的还是原生ECC算法 ，对数据的处理用国密算法，这种做目前版本是否支持呢？

1. 如果你要用fabric-sdk-java的话，你需要改造fabric-sdk-java；你需要找对应的国密java库，可以参考一下这个：
https://github.com/guanzhi/GmSSL

2. 至于你说的第二点仅仅是加密数据处理，没必要改动源码；你可以在智能合约里去实现加解密。
